export interface StateInfo {
  name: string;
  slug: string;
  title: string;
  description: string;
  bannerImage: string;
  majorCities: string[];
  popularRoutes: { from: string; to: string }[];
  step1: { title: string; text: string; image: string };
  step2: { title: string; text: string; image: string };
  step3: { title: string; text: string; image: string };
}

export const statesData: Record<string, StateInfo> = {
  alabama: {
    name: 'Alabama',
    slug: 'alabama',
    title: 'Alabama Car Shipping Services',
    description: 'Experience safe, reliable auto transport services to and from Alabama with BMD Freight, one of the most trusted auto transport companies in the vehicle shipping industry.',
    bannerImage: '/assets/state/alabama.webp',
    majorCities: ['Birmingham', 'Montgomery', 'Mobile', 'Huntsville', 'Tuscaloosa'],
    popularRoutes: [{ from: 'Alabama to Florida', to: 'Florida to Alabama' }, { from: 'Alabama to Texas', to: 'Texas to Alabama' }],
    step1: { title: 'Get your instant Alabama car shipping quote', text: 'Book with Alabama\'s most reliable auto transport company using our vehicle transport cost calculator for a free, no-obligation quote! Secure your Alabama auto transport services in seconds.', image: '/assets/state/alabama-1.webp' },
    step2: { title: 'We arrange auto shipping that Alabama residents rely on', text: 'Regular car transport is one thing. BMD Freight offers unmatched flexibility, a vast carrier network of trusted auto transporters, and a reputation for excellence that no other Alabama car shipping company can match.', image: '/assets/state/alabama-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Alabama is hassle-free with BMD Freight. Pay your deposit when you book, and settle the balance with your driver at pickup or delivery. No surprises, just affordable, dependable Alabama shipping!', image: '/assets/state/alabama-3.webp' }
  },
  alaska: {
    name: 'Alaska',
    slug: 'alaska',
    title: 'Alaska Car Shipping Services',
    description: 'Shipping a car to or from Alaska requires specialized port-to-port logistics. BMD Freight coordinates reliable transport for Anchorage, Fairbanks, and Juneau with experienced carriers.',
    bannerImage: '/assets/state/alaska.webp',
    majorCities: ['Anchorage', 'Fairbanks', 'Juneau', 'Wasilla', 'Sitka'],
    popularRoutes: [{ from: 'Alaska to Washington', to: 'Washington to Alaska' }, { from: 'Alaska to California', to: 'California to Alaska' }],
    step1: { title: 'Get your instant Alaska car shipping quote', text: 'Book with Alaska\'s most reliable auto transport company for a free, no-obligation quote! Secure your Alaska auto transport services in seconds.', image: '/assets/state/alaska-1.webp' },
    step2: { title: 'We arrange auto shipping that Alaska residents rely on', text: 'BMD Freight offers unmatched flexibility, a vast carrier network of trusted auto transporters, and a reputation for excellence that no other Alaska car shipping company can match.', image: '/assets/state/alaska-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Alaska is hassle-free with BMD Freight. Pay your deposit when you book, and settle the balance with your driver at pickup or delivery.', image: '/assets/state/alaska-3.webp' }
  },
  arizona: {
    name: 'Arizona',
    slug: 'arizona',
    title: 'Arizona Car Shipping Services',
    description: 'Arizona car shipping made simple. From Phoenix to Tucson and Scottsdale to Flagstaff, BMD Freight offers affordable, reliable auto transport across the Grand Canyon State.',
    bannerImage: '/assets/state/arizona.webp',
    majorCities: ['Phoenix', 'Tucson', 'Scottsdale', 'Mesa', 'Flagstaff'],
    popularRoutes: [{ from: 'Arizona to California', to: 'California to Arizona' }, { from: 'Arizona to Texas', to: 'Texas to Arizona' }],
    step1: { title: 'Get your instant Arizona car shipping quote', text: 'Book with Arizona\'s most reliable auto transport company for a free, no-obligation quote! Secure your Arizona auto transport services in seconds.', image: '/assets/state/arizona-1.webp' },
    step2: { title: 'We arrange auto shipping that Arizona residents rely on', text: 'BMD Freight offers unmatched flexibility, a vast carrier network of trusted auto transporters, and a reputation for excellence that no other Arizona car shipping company can match.', image: '/assets/state/arizona-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Arizona is hassle-free with BMD Freight. Pay your deposit when you book, and settle the balance with your driver at pickup or delivery.', image: '/assets/state/arizona-3.webp' }
  },
  arkansas: {
    name: 'Arkansas',
    slug: 'arkansas',
    title: 'Arkansas Car Shipping Services',
    description: 'Need to ship a car to or from Arkansas? BMD Freight serves Little Rock, Fayetteville, and Fort Smith with professional auto transport services at competitive rates.',
    bannerImage: '/assets/state/arkansas.webp',
    majorCities: ['Little Rock', 'Fayetteville', 'Fort Smith', 'Springdale', 'Jonesboro'],
    popularRoutes: [{ from: 'Arkansas to Texas', to: 'Texas to Arkansas' }, { from: 'Arkansas to Tennessee', to: 'Tennessee to Arkansas' }],
    step1: { title: 'Get your instant Arkansas car shipping quote', text: 'Book with Arkansas\'s most reliable auto transport company for a free, no-obligation quote! Secure your Arkansas auto transport services in seconds.', image: '/assets/state/arkansas-1.webp' },
    step2: { title: 'We arrange auto shipping that Arkansas residents rely on', text: 'BMD Freight offers unmatched flexibility, a vast carrier network of trusted auto transporters, and a reputation for excellence that no other Arkansas car shipping company can match.', image: '/assets/state/arkansas-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Arkansas is hassle-free with BMD Freight. Pay your deposit when you book, and settle the balance with your driver at pickup or delivery.', image: '/assets/state/arkansas-3.webp' }
  },
  california: {
    name: 'California',
    slug: 'california',
    title: 'California Auto Transport Services',
    description: 'When it comes to shipping your vehicle to or from California, BMD Freight stands out as a trusted and reliable choice. Whether you\'re moving across the state or across the country, our professional auto transport services ensure your vehicle arrives safely and on time.',
    bannerImage: '/assets/state/california.webp',
    majorCities: ['Los Angeles', 'San Francisco', 'San Diego', 'Sacramento', 'San Jose'],
    popularRoutes: [{ from: 'California to Texas', to: 'Texas to California' }, { from: 'California to Florida', to: 'Florida to California' }],
    step1: { title: 'Get your instant California car shipping quote', text: 'Book with California\'s most reliable auto transport company for a free, no-obligation quote! Secure your California auto transport services in seconds.', image: '/assets/state/california-1.webp' },
    step2: { title: 'We arrange auto shipping that California residents rely on', text: 'BMD Freight offers unmatched flexibility, a vast carrier network of trusted auto transporters, and a reputation for excellence that no other California car shipping company can match.', image: '/assets/state/california-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within California is hassle-free with BMD Freight. Pay your deposit when you book, and settle the balance with your driver at pickup or delivery.', image: '/assets/state/california-3.webp' }
  },
  colorado: {
    name: 'Colorado',
    slug: 'colorado',
    title: 'Colorado Car Shipping Services',
    description: 'Transport your vehicle to or from Colorado with confidence. BMD Freight serves Denver, Colorado Springs, Boulder, and Fort Collins with reliable mountain-state auto shipping.',
    bannerImage: '/assets/state/colorado.webp',
    majorCities: ['Denver', 'Colorado Springs', 'Aurora', 'Boulder', 'Fort Collins'],
    popularRoutes: [{ from: 'Colorado to Texas', to: 'Texas to Colorado' }, { from: 'Colorado to California', to: 'California to Colorado' }],
    step1: { title: 'Get your instant Colorado car shipping quote', text: 'Book with Colorado\'s most reliable auto transport company for a free, no-obligation quote! Secure your Colorado auto transport services in seconds.', image: '/assets/state/colorado-1.webp' },
    step2: { title: 'We arrange auto shipping that Colorado residents rely on', text: 'BMD Freight offers unmatched flexibility, a vast carrier network of trusted auto transporters, and a reputation for excellence that no other Colorado car shipping company can match.', image: '/assets/state/colorado-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Colorado is hassle-free with BMD Freight. Pay your deposit when you book, and settle the balance with your driver at pickup or delivery.', image: '/assets/state/colorado-3.webp' }
  },
  connecticut: {
    name: 'Connecticut',
    slug: 'connecticut',
    title: 'Connecticut Car Shipping Services',
    description: 'Car shipping in Connecticut is easy with BMD Freight. We transport vehicles to and from Hartford, New Haven, Stamford, and Bridgeport with door-to-door service.',
    bannerImage: '/assets/state/connecticut.webp',
    majorCities: ['Hartford', 'New Haven', 'Stamford', 'Bridgeport', 'Waterbury'],
    popularRoutes: [{ from: 'Connecticut to Florida', to: 'Florida to Connecticut' }, { from: 'Connecticut to New York', to: 'New York to Connecticut' }],
    step1: { title: 'Get your instant Connecticut car shipping quote', text: 'Book with Connecticut\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/connecticut-1.webp' },
    step2: { title: 'We arrange auto shipping that Connecticut residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence that no other Connecticut car shipping company can match.', image: '/assets/state/connecticut-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Connecticut is hassle-free with BMD Freight.', image: '/assets/state/connecticut-3.webp' }
  },
  delaware: {
    name: 'Delaware',
    slug: 'delaware',
    title: 'Delaware Car Shipping Services',
    description: 'Small state, big service. BMD Freight provides reliable car shipping to and from Wilmington, Dover, and Newark, Delaware with competitive pricing.',
    bannerImage: '/assets/state/delaware.webp',
    majorCities: ['Wilmington', 'Dover', 'Newark', 'Middletown', 'Bear'],
    popularRoutes: [{ from: 'Delaware to Florida', to: 'Florida to Delaware' }, { from: 'Delaware to New York', to: 'New York to Delaware' }],
    step1: { title: 'Get your instant Delaware car shipping quote', text: 'Book with Delaware\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/delaware-1.webp' },
    step2: { title: 'We arrange auto shipping that Delaware residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/delaware-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Delaware is hassle-free with BMD Freight.', image: '/assets/state/delaware-3.webp' }
  },
  florida: {
    name: 'Florida',
    slug: 'florida',
    title: 'Florida Auto Transport Services',
    description: 'Shipping a car to or from Florida doesn\'t have to be complicated. Whether you\'re relocating, purchasing a vehicle online, or heading south for the winter, BMD Freight offers reliable, affordable, and efficient auto transport services tailored to your needs.',
    bannerImage: '/assets/state/florida.webp',
    majorCities: ['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'Fort Lauderdale'],
    popularRoutes: [{ from: 'Florida to New York', to: 'New York to Florida' }, { from: 'Florida to California', to: 'California to Florida' }],
    step1: { title: 'Get your instant Florida car shipping quote', text: 'Book with Florida\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/florida-1.webp' },
    step2: { title: 'We arrange auto shipping that Florida residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence that no other Florida car shipping company can match.', image: '/assets/state/florida-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Florida is hassle-free with BMD Freight.', image: '/assets/state/florida-3.webp' }
  },
  georgia: {
    name: 'Georgia',
    slug: 'georgia',
    title: 'Georgia Car Shipping Services',
    description: 'Car shipping to and from Georgia is seamless with BMD Freight. We serve Atlanta, Savannah, Augusta, and Columbus with professional transport services.',
    bannerImage: '/assets/state/georgia.webp',
    majorCities: ['Atlanta', 'Savannah', 'Augusta', 'Columbus', 'Macon'],
    popularRoutes: [{ from: 'Georgia to Florida', to: 'Florida to Georgia' }, { from: 'Georgia to Texas', to: 'Texas to Georgia' }],
    step1: { title: 'Get your instant Georgia car shipping quote', text: 'Book with Georgia\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/georgia-1.webp' },
    step2: { title: 'We arrange auto shipping that Georgia residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/georgia-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Georgia is hassle-free with BMD Freight.', image: '/assets/state/georgia-3.webp' }
  },
  hawaii: {
    name: 'Hawaii',
    slug: 'hawaii',
    title: 'Hawaii Car Shipping Services',
    description: 'Shipping a car to or from Hawaii requires port coordination. BMD Freight manages the logistics for Honolulu, Hilo, and Kona with trusted port-to-port carriers.',
    bannerImage: '/assets/state/hawaii.webp',
    majorCities: ['Honolulu', 'Hilo', 'Kailua', 'Kahului', 'Kona'],
    popularRoutes: [{ from: 'Hawaii to California', to: 'California to Hawaii' }, { from: 'Hawaii to Washington', to: 'Washington to Hawaii' }],
    step1: { title: 'Get your instant Hawaii car shipping quote', text: 'Book with Hawaii\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/hawaii-1.webp' },
    step2: { title: 'We arrange auto shipping that Hawaii residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/hawaii-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Hawaii is hassle-free with BMD Freight.', image: '/assets/state/hawaii-3.webp' }
  },
  idaho: {
    name: 'Idaho',
    slug: 'idaho',
    title: 'Idaho Car Shipping Services',
    description: 'Reliable car shipping to and from Idaho. BMD Freight serves Boise, Idaho Falls, Nampa, and Twin Falls with safe, on-time vehicle transport.',
    bannerImage: '/assets/state/idaho.webp',
    majorCities: ['Boise', 'Idaho Falls', 'Nampa', 'Meridian', 'Twin Falls'],
    popularRoutes: [{ from: 'Idaho to Washington', to: 'Washington to Idaho' }, { from: 'Idaho to California', to: 'California to Idaho' }],
    step1: { title: 'Get your instant Idaho car shipping quote', text: 'Book with Idaho\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/idaho-1.webp' },
    step2: { title: 'We arrange auto shipping that Idaho residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/idaho-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Idaho is hassle-free with BMD Freight.', image: '/assets/state/idaho-3.webp' }
  },
  illinois: {
    name: 'Illinois',
    slug: 'illinois',
    title: 'Illinois Car Shipping Services',
    description: 'Illinois car shipping made easy. From Chicago to Springfield and Peoria to Rockford, BMD Freight provides professional auto transport throughout the Prairie State.',
    bannerImage: '/assets/state/illinois.webp',
    majorCities: ['Chicago', 'Springfield', 'Peoria', 'Rockford', 'Naperville'],
    popularRoutes: [{ from: 'Illinois to Florida', to: 'Florida to Illinois' }, { from: 'Illinois to Texas', to: 'Texas to Illinois' }],
    step1: { title: 'Get your instant Illinois car shipping quote', text: 'Book with Illinois\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/illinois-1.webp' },
    step2: { title: 'We arrange auto shipping that Illinois residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/illinois-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Illinois is hassle-free with BMD Freight.', image: '/assets/state/illinois-3.webp' }
  },
  indiana: {
    name: 'Indiana',
    slug: 'indiana',
    title: 'Indiana Car Shipping Services',
    description: 'Ship your car to or from Indiana with BMD Freight. We serve Indianapolis, Fort Wayne, Evansville, and South Bend with reliable door-to-door transport.',
    bannerImage: '/assets/state/indiana.webp',
    majorCities: ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend', 'Bloomington'],
    popularRoutes: [{ from: 'Indiana to Florida', to: 'Florida to Indiana' }, { from: 'Indiana to Texas', to: 'Texas to Indiana' }],
    step1: { title: 'Get your instant Indiana car shipping quote', text: 'Book with Indiana\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/indiana-1.webp' },
    step2: { title: 'We arrange auto shipping that Indiana residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/indiana-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Indiana is hassle-free with BMD Freight.', image: '/assets/state/indiana-3.webp' }
  },
  iowa: {
    name: 'Iowa',
    slug: 'iowa',
    title: 'Iowa Car Shipping Services',
    description: 'Iowa car shipping services from BMD Freight. We transport vehicles to and from Des Moines, Cedar Rapids, Davenport, and Sioux City safely and efficiently.',
    bannerImage: '/assets/state/iowa.webp',
    majorCities: ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City', 'Iowa City'],
    popularRoutes: [{ from: 'Iowa to Texas', to: 'Texas to Iowa' }, { from: 'Iowa to California', to: 'California to Iowa' }],
    step1: { title: 'Get your instant Iowa car shipping quote', text: 'Book with Iowa\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/iowa-1.webp' },
    step2: { title: 'We arrange auto shipping that Iowa residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/iowa-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Iowa is hassle-free with BMD Freight.', image: '/assets/state/iowa-3.webp' }
  },
  kansas: {
    name: 'Kansas',
    slug: 'kansas',
    title: 'Kansas Car Shipping Services',
    description: 'Auto transport to and from Kansas is simple with BMD Freight. We serve Wichita, Kansas City, Topeka, and Lawrence with competitive rates and reliable carriers.',
    bannerImage: '/assets/state/kansas.webp',
    majorCities: ['Wichita', 'Kansas City', 'Topeka', 'Lawrence', 'Olathe'],
    popularRoutes: [{ from: 'Kansas to Texas', to: 'Texas to Kansas' }, { from: 'Kansas to Colorado', to: 'Colorado to Kansas' }],
    step1: { title: 'Get your instant Kansas car shipping quote', text: 'Book with Kansas\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/kansas-1.webp' },
    step2: { title: 'We arrange auto shipping that Kansas residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/kansas-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Kansas is hassle-free with BMD Freight.', image: '/assets/state/kansas-3.webp' }
  },
  kentucky: {
    name: 'Kentucky',
    slug: 'kentucky',
    title: 'Kentucky Car Shipping Services',
    description: 'Car shipping in Kentucky made reliable. BMD Freight moves vehicles to and from Louisville, Lexington, Bowling Green, and Frankfort with professional service.',
    bannerImage: '/assets/state/kentucky.webp',
    majorCities: ['Louisville', 'Lexington', 'Bowling Green', 'Frankfort', 'Owensboro'],
    popularRoutes: [{ from: 'Kentucky to Florida', to: 'Florida to Kentucky' }, { from: 'Kentucky to Texas', to: 'Texas to Kentucky' }],
    step1: { title: 'Get your instant Kentucky car shipping quote', text: 'Book with Kentucky\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/kentucky-1.webp' },
    step2: { title: 'We arrange auto shipping that Kentucky residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/kentucky-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Kentucky is hassle-free with BMD Freight.', image: '/assets/state/kentucky-3.webp' }
  },
  louisiana: {
    name: 'Louisiana',
    slug: 'louisiana',
    title: 'Louisiana Car Shipping Services',
    description: 'Ship your car to or from Louisiana with BMD Freight. We serve New Orleans, Baton Rouge, Shreveport, and Lafayette with experienced Gulf Coast carriers.',
    bannerImage: '/assets/state/louisiana.webp',
    majorCities: ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette', 'Lake Charles'],
    popularRoutes: [{ from: 'Louisiana to Texas', to: 'Texas to Louisiana' }, { from: 'Louisiana to Florida', to: 'Florida to Louisiana' }],
    step1: { title: 'Get your instant Louisiana car shipping quote', text: 'Book with Louisiana\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/louisiana-1.webp' },
    step2: { title: 'We arrange auto shipping that Louisiana residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/louisiana-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Louisiana is hassle-free with BMD Freight.', image: '/assets/state/louisiana-3.webp' }
  },
  maine: {
    name: 'Maine',
    slug: 'maine',
    title: 'Maine Car Shipping Services',
    description: 'Maine car shipping with BMD Freight. We transport vehicles to and from Portland, Bangor, Augusta, and Lewiston with reliable New England service.',
    bannerImage: '/assets/state/maine.webp',
    majorCities: ['Portland', 'Bangor', 'Augusta', 'Lewiston', 'South Portland'],
    popularRoutes: [{ from: 'Maine to Florida', to: 'Florida to Maine' }, { from: 'Maine to New York', to: 'New York to Maine' }],
    step1: { title: 'Get your instant Maine car shipping quote', text: 'Book with Maine\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/maine-1.webp' },
    step2: { title: 'We arrange auto shipping that Maine residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/maine-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Maine is hassle-free with BMD Freight.', image: '/assets/state/maine-3.webp' }
  },
  maryland: {
    name: 'Maryland',
    slug: 'maryland',
    title: 'Maryland Car Shipping Services',
    description: 'Auto transport to and from Maryland made simple. BMD Freight serves Baltimore, Frederick, Rockville, and Gaithersburg with professional door-to-door service.',
    bannerImage: '/assets/state/maryland.webp',
    majorCities: ['Baltimore', 'Frederick', 'Rockville', 'Gaithersburg', 'Annapolis'],
    popularRoutes: [{ from: 'Maryland to Florida', to: 'Florida to Maryland' }, { from: 'Maryland to Texas', to: 'Texas to Maryland' }],
    step1: { title: 'Get your instant Maryland car shipping quote', text: 'Book with Maryland\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/maryland-1.webp' },
    step2: { title: 'We arrange auto shipping that Maryland residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/maryland-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Maryland is hassle-free with BMD Freight.', image: '/assets/state/maryland-3.webp' }
  },
  massachusetts: {
    name: 'Massachusetts',
    slug: 'massachusetts',
    title: 'Massachusetts Car Shipping Services',
    description: 'Massachusetts car shipping experts. BMD Freight moves vehicles to and from Boston, Worcester, Springfield, and Cambridge with reliable New England transport.',
    bannerImage: '/assets/state/massachusetts.webp',
    majorCities: ['Boston', 'Worcester', 'Springfield', 'Cambridge', 'Lowell'],
    popularRoutes: [{ from: 'Massachusetts to Florida', to: 'Florida to Massachusetts' }, { from: 'Massachusetts to New York', to: 'New York to Massachusetts' }],
    step1: { title: 'Get your instant Massachusetts car shipping quote', text: 'Book with Massachusetts\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/massachusetts-1.webp' },
    step2: { title: 'We arrange auto shipping that Massachusetts residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/massachusetts-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Massachusetts is hassle-free with BMD Freight.', image: '/assets/state/massachusetts-3.webp' }
  },
  michigan: {
    name: 'Michigan',
    slug: 'michigan',
    title: 'Michigan Car Shipping Services',
    description: 'Car shipping to and from Michigan with BMD Freight. We serve Detroit, Grand Rapids, Ann Arbor, and Lansing with professional auto transport services.',
    bannerImage: '/assets/state/michigan.webp',
    majorCities: ['Detroit', 'Grand Rapids', 'Ann Arbor', 'Lansing', 'Flint'],
    popularRoutes: [{ from: 'Michigan to Florida', to: 'Florida to Michigan' }, { from: 'Michigan to Texas', to: 'Texas to Michigan' }],
    step1: { title: 'Get your instant Michigan car shipping quote', text: 'Book with Michigan\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/michigan-1.webp' },
    step2: { title: 'We arrange auto shipping that Michigan residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/michigan-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Michigan is hassle-free with BMD Freight.', image: '/assets/state/michigan-3.webp' }
  },
  minnesota: {
    name: 'Minnesota',
    slug: 'minnesota',
    title: 'Minnesota Car Shipping Services',
    description: 'Reliable car shipping in Minnesota. BMD Freight serves Minneapolis, Saint Paul, Rochester, and Duluth with safe, on-time vehicle transport year-round.',
    bannerImage: '/assets/state/minnesota.webp',
    majorCities: ['Minneapolis', 'Saint Paul', 'Rochester', 'Duluth', 'Bloomington'],
    popularRoutes: [{ from: 'Minnesota to Florida', to: 'Florida to Minnesota' }, { from: 'Minnesota to Texas', to: 'Texas to Minnesota' }],
    step1: { title: 'Get your instant Minnesota car shipping quote', text: 'Book with Minnesota\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/minnesota-1.webp' },
    step2: { title: 'We arrange auto shipping that Minnesota residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/minnesota-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Minnesota is hassle-free with BMD Freight.', image: '/assets/state/minnesota-3.webp' }
  },
  mississippi: {
    name: 'Mississippi',
    slug: 'mississippi',
    title: 'Mississippi Car Shipping Services',
    description: 'Auto transport to and from Mississippi made easy. BMD Freight serves Jackson, Gulfport, Hattiesburg, and Biloxi with professional Gulf Coast carriers.',
    bannerImage: '/assets/state/mississippi.webp',
    majorCities: ['Jackson', 'Gulfport', 'Hattiesburg', 'Biloxi', 'Southaven'],
    popularRoutes: [{ from: 'Mississippi to Texas', to: 'Texas to Mississippi' }, { from: 'Mississippi to Florida', to: 'Florida to Mississippi' }],
    step1: { title: 'Get your instant Mississippi car shipping quote', text: 'Book with Mississippi\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/mississippi-1.webp' },
    step2: { title: 'We arrange auto shipping that Mississippi residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/mississippi-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Mississippi is hassle-free with BMD Freight.', image: '/assets/state/mississippi-3.webp' }
  },
  missouri: {
    name: 'Missouri',
    slug: 'missouri',
    title: 'Missouri Car Shipping Services',
    description: 'Car shipping in Missouri with BMD Freight. We transport vehicles to and from Kansas City, Saint Louis, Springfield, and Columbia with competitive rates.',
    bannerImage: '/assets/state/missouri.webp',
    majorCities: ['Kansas City', 'Saint Louis', 'Springfield', 'Columbia', 'Jefferson City'],
    popularRoutes: [{ from: 'Missouri to Texas', to: 'Texas to Missouri' }, { from: 'Missouri to Florida', to: 'Florida to Missouri' }],
    step1: { title: 'Get your instant Missouri car shipping quote', text: 'Book with Missouri\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/missouri-1.webp' },
    step2: { title: 'We arrange auto shipping that Missouri residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/missouri-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Missouri is hassle-free with BMD Freight.', image: '/assets/state/missouri-3.webp' }
  },
  montana: {
    name: 'Montana',
    slug: 'montana',
    title: 'Montana Car Shipping Services',
    description: 'Montana car shipping services from BMD Freight. We serve Billings, Missoula, Great Falls, and Bozeman with experienced carriers for rural routes.',
    bannerImage: '/assets/state/montana.webp',
    majorCities: ['Billings', 'Missoula', 'Great Falls', 'Bozeman', 'Helena'],
    popularRoutes: [{ from: 'Montana to Washington', to: 'Washington to Montana' }, { from: 'Montana to California', to: 'California to Montana' }],
    step1: { title: 'Get your instant Montana car shipping quote', text: 'Book with Montana\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/montana-1.webp' },
    step2: { title: 'We arrange auto shipping that Montana residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/montana-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Montana is hassle-free with BMD Freight.', image: '/assets/state/montana-3.webp' }
  },
  nebraska: {
    name: 'Nebraska',
    slug: 'nebraska',
    title: 'Nebraska Car Shipping Services',
    description: 'Ship your car to or from Nebraska with BMD Freight. We serve Omaha, Lincoln, Bellevue, and Grand Island with reliable Midwest auto transport.',
    bannerImage: '/assets/state/nebraska.webp',
    majorCities: ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island', 'Kearney'],
    popularRoutes: [{ from: 'Nebraska to Texas', to: 'Texas to Nebraska' }, { from: 'Nebraska to California', to: 'California to Nebraska' }],
    step1: { title: 'Get your instant Nebraska car shipping quote', text: 'Book with Nebraska\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/nebraska-1.webp' },
    step2: { title: 'We arrange auto shipping that Nebraska residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/nebraska-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Nebraska is hassle-free with BMD Freight.', image: '/assets/state/nebraska-3.webp' }
  },
  nevada: {
    name: 'Nevada',
    slug: 'nevada',
    title: 'Nevada Car Shipping Services',
    description: 'Nevada car shipping made simple. BMD Freight moves vehicles to and from Las Vegas, Reno, Henderson, and Carson City with fast, reliable service.',
    bannerImage: '/assets/state/nevada.webp',
    majorCities: ['Las Vegas', 'Reno', 'Henderson', 'Carson City', 'North Las Vegas'],
    popularRoutes: [{ from: 'Nevada to California', to: 'California to Nevada' }, { from: 'Nevada to Texas', to: 'Texas to Nevada' }],
    step1: { title: 'Get your instant Nevada car shipping quote', text: 'Book with Nevada\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/nevada-1.webp' },
    step2: { title: 'We arrange auto shipping that Nevada residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/nevada-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Nevada is hassle-free with BMD Freight.', image: '/assets/state/nevada-3.webp' }
  },
  'new-hampshire': {
    name: 'New Hampshire',
    slug: 'new-hampshire',
    title: 'New Hampshire Car Shipping Services',
    description: 'Car shipping to and from New Hampshire with BMD Freight. We serve Manchester, Nashua, Concord, and Portsmouth with professional New England transport.',
    bannerImage: '/assets/state/new.webp',
    majorCities: ['Manchester', 'Nashua', 'Concord', 'Portsmouth', 'Dover'],
    popularRoutes: [{ from: 'New Hampshire to Florida', to: 'Florida to New Hampshire' }, { from: 'New Hampshire to New York', to: 'New York to New Hampshire' }],
    step1: { title: 'Get your instant New Hampshire car shipping quote', text: 'Book with New Hampshire\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/new-1.webp' },
    step2: { title: 'We arrange auto shipping that New Hampshire residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/new-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within New Hampshire is hassle-free with BMD Freight.', image: '/assets/state/new-3.webp' }
  },
  'new-jersey': {
    name: 'New Jersey',
    slug: 'new-jersey',
    title: 'New Jersey Car Shipping Services',
    description: 'New Jersey auto transport experts. BMD Freight ships cars to and from Newark, Jersey City, Trenton, and Atlantic City with reliable door-to-door service.',
    bannerImage: '/assets/state/jersey.webp',
    majorCities: ['Newark', 'Jersey City', 'Trenton', 'Atlantic City', 'Paterson'],
    popularRoutes: [{ from: 'New Jersey to Florida', to: 'Florida to New Jersey' }, { from: 'New Jersey to California', to: 'California to New Jersey' }],
    step1: { title: 'Get your instant New Jersey car shipping quote', text: 'Book with New Jersey\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/jersey-1.webp' },
    step2: { title: 'We arrange auto shipping that New Jersey residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/jersey-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within New Jersey is hassle-free with BMD Freight.', image: '/assets/state/jersey-3.webp' }
  },
  'new-mexico': {
    name: 'New Mexico',
    slug: 'new-mexico',
    title: 'New Mexico Car Shipping Services',
    description: 'Ship your car to or from New Mexico with BMD Freight. We serve Albuquerque, Santa Fe, Las Cruces, and Roswell with professional Southwest auto transport.',
    bannerImage: '/assets/state/mexico.webp',
    majorCities: ['Albuquerque', 'Santa Fe', 'Las Cruces', 'Roswell', 'Taos'],
    popularRoutes: [{ from: 'New Mexico to Texas', to: 'Texas to New Mexico' }, { from: 'New Mexico to California', to: 'California to New Mexico' }],
    step1: { title: 'Get your instant New Mexico car shipping quote', text: 'Book with New Mexico\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/mexico-1.webp' },
    step2: { title: 'We arrange auto shipping that New Mexico residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/mexico-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within New Mexico is hassle-free with BMD Freight.', image: '/assets/state/mexico-3.webp' }
  },
  'new-york': {
    name: 'New York',
    slug: 'new-york',
    title: 'New York Car Shipping Services',
    description: 'New York car shipping made easy. From NYC to Buffalo and Albany to Rochester, BMD Freight provides professional auto transport throughout the Empire State.',
    bannerImage: '/assets/state/york.webp',
    majorCities: ['New York City', 'Buffalo', 'Albany', 'Rochester', 'Syracuse'],
    popularRoutes: [{ from: 'New York to Florida', to: 'Florida to New York' }, { from: 'New York to California', to: 'California to New York' }],
    step1: { title: 'Get your instant New York car shipping quote', text: 'Book with New York\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/york-1.webp' },
    step2: { title: 'We arrange auto shipping that New York residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/york-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within New York is hassle-free with BMD Freight.', image: '/assets/state/york-3.webp' }
  },
  'north-carolina': {
    name: 'North Carolina',
    slug: 'north-carolina',
    title: 'North Carolina Car Shipping Services',
    description: 'Car shipping in North Carolina with BMD Freight. We serve Charlotte, Raleigh, Greensboro, and Wilmington with reliable East Coast auto transport.',
    bannerImage: '/assets/state/carolina.webp',
    majorCities: ['Charlotte', 'Raleigh', 'Greensboro', 'Wilmington', 'Durham'],
    popularRoutes: [{ from: 'North Carolina to Florida', to: 'Florida to North Carolina' }, { from: 'North Carolina to New York', to: 'New York to North Carolina' }],
    step1: { title: 'Get your instant North Carolina car shipping quote', text: 'Book with North Carolina\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/carolina-1.webp' },
    step2: { title: 'We arrange auto shipping that North Carolina residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/carolina-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within North Carolina is hassle-free with BMD Freight.', image: '/assets/state/carolina-3.webp' }
  },
  'north-dakota': {
    name: 'North Dakota',
    slug: 'north-dakota',
    title: 'North Dakota Car Shipping Services',
    description: 'Auto transport to and from North Dakota. BMD Freight serves Fargo, Bismarck, Grand Forks, and Minot with experienced carriers for northern routes.',
    bannerImage: '/assets/state/dakota.webp',
    majorCities: ['Fargo', 'Bismarck', 'Grand Forks', 'Minot', 'Dickinson'],
    popularRoutes: [{ from: 'North Dakota to Texas', to: 'Texas to North Dakota' }, { from: 'North Dakota to Washington', to: 'Washington to North Dakota' }],
    step1: { title: 'Get your instant North Dakota car shipping quote', text: 'Book with North Dakota\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/dakota-1.webp' },
    step2: { title: 'We arrange auto shipping that North Dakota residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/dakota-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within North Dakota is hassle-free with BMD Freight.', image: '/assets/state/dakota-3.webp' }
  },
  ohio: {
    name: 'Ohio',
    slug: 'ohio',
    title: 'Ohio Car Shipping Services',
    description: 'Ohio car shipping experts. BMD Freight moves vehicles to and from Columbus, Cleveland, Cincinnati, and Toledo with professional Midwest transport.',
    bannerImage: '/assets/state/ohio.webp',
    majorCities: ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron'],
    popularRoutes: [{ from: 'Ohio to Florida', to: 'Florida to Ohio' }, { from: 'Ohio to Texas', to: 'Texas to Ohio' }],
    step1: { title: 'Get your instant Ohio car shipping quote', text: 'Book with Ohio\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/ohio-1.webp' },
    step2: { title: 'We arrange auto shipping that Ohio residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/ohio-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Ohio is hassle-free with BMD Freight.', image: '/assets/state/ohio-3.webp' }
  },
  oklahoma: {
    name: 'Oklahoma',
    slug: 'oklahoma',
    title: 'Oklahoma Car Shipping Services',
    description: 'Ship your car to or from Oklahoma with BMD Freight. We serve Oklahoma City, Tulsa, Norman, and Stillwater with reliable Southwest auto transport.',
    bannerImage: '/assets/state/oklahoma.webp',
    majorCities: ['Oklahoma City', 'Tulsa', 'Norman', 'Stillwater', 'Lawton'],
    popularRoutes: [{ from: 'Oklahoma to Texas', to: 'Texas to Oklahoma' }, { from: 'Oklahoma to California', to: 'California to Oklahoma' }],
    step1: { title: 'Get your instant Oklahoma car shipping quote', text: 'Book with Oklahoma\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/oklahoma-1.webp' },
    step2: { title: 'We arrange auto shipping that Oklahoma residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/oklahoma-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Oklahoma is hassle-free with BMD Freight.', image: '/assets/state/oklahoma-3.webp' }
  },
  oregon: {
    name: 'Oregon',
    slug: 'oregon',
    title: 'Oregon Car Shipping Services',
    description: 'Oregon car shipping made simple. BMD Freight serves Portland, Eugene, Salem, and Bend with professional Pacific Northwest auto transport.',
    bannerImage: '/assets/state/oregon.webp',
    majorCities: ['Portland', 'Eugene', 'Salem', 'Bend', 'Medford'],
    popularRoutes: [{ from: 'Oregon to California', to: 'California to Oregon' }, { from: 'Oregon to Texas', to: 'Texas to Oregon' }],
    step1: { title: 'Get your instant Oregon car shipping quote', text: 'Book with Oregon\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/oregon-1.webp' },
    step2: { title: 'We arrange auto shipping that Oregon residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/oregon-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Oregon is hassle-free with BMD Freight.', image: '/assets/state/oregon-3.webp' }
  },
  pennsylvania: {
    name: 'Pennsylvania',
    slug: 'pennsylvania',
    title: 'Pennsylvania Car Shipping Services',
    description: 'Car shipping to and from Pennsylvania with BMD Freight. We serve Philadelphia, Pittsburgh, Allentown, and Harrisburg with reliable East Coast transport.',
    bannerImage: '/assets/state/pennsylvania.webp',
    majorCities: ['Philadelphia', 'Pittsburgh', 'Allentown', 'Harrisburg', 'Erie'],
    popularRoutes: [{ from: 'Pennsylvania to Florida', to: 'Florida to Pennsylvania' }, { from: 'Pennsylvania to Texas', to: 'Texas to Pennsylvania' }],
    step1: { title: 'Get your instant Pennsylvania car shipping quote', text: 'Book with Pennsylvania\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/pennsylvania-1.webp' },
    step2: { title: 'We arrange auto shipping that Pennsylvania residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/pennsylvania-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Pennsylvania is hassle-free with BMD Freight.', image: '/assets/state/pennsylvania-3.webp' }
  },
  'rhode-island': {
    name: 'Rhode Island',
    slug: 'rhode-island',
    title: 'Rhode Island Car Shipping Services',
    description: 'Rhode Island auto transport with BMD Freight. We serve Providence, Warwick, Cranston, and Newport with professional New England car shipping.',
    bannerImage: '/assets/state/rhode.webp',
    majorCities: ['Providence', 'Warwick', 'Cranston', 'Newport', 'Pawtucket'],
    popularRoutes: [{ from: 'Rhode Island to Florida', to: 'Florida to Rhode Island' }, { from: 'Rhode Island to New York', to: 'New York to Rhode Island' }],
    step1: { title: 'Get your instant Rhode Island car shipping quote', text: 'Book with Rhode Island\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/rhode-1.webp' },
    step2: { title: 'We arrange auto shipping that Rhode Island residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/rhode-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Rhode Island is hassle-free with BMD Freight.', image: '/assets/state/rhode-3.webp' }
  },
  'south-carolina': {
    name: 'South Carolina',
    slug: 'south-carolina',
    title: 'South Carolina Car Shipping Services',
    description: 'Car shipping in South Carolina made easy. BMD Freight serves Charleston, Columbia, Greenville, and Myrtle Beach with reliable Southeast auto transport.',
    bannerImage: '/assets/state/carolina.webp',
    majorCities: ['Charleston', 'Columbia', 'Greenville', 'Myrtle Beach', 'Spartanburg'],
    popularRoutes: [{ from: 'South Carolina to Florida', to: 'Florida to South Carolina' }, { from: 'South Carolina to New York', to: 'New York to South Carolina' }],
    step1: { title: 'Get your instant South Carolina car shipping quote', text: 'Book with South Carolina\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/carolina-1.webp' },
    step2: { title: 'We arrange auto shipping that South Carolina residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/carolina-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within South Carolina is hassle-free with BMD Freight.', image: '/assets/state/carolina-3.webp' }
  },
  'south-dakota': {
    name: 'South Dakota',
    slug: 'south-dakota',
    title: 'South Dakota Car Shipping Services',
    description: 'Auto transport to and from South Dakota. BMD Freight serves Sioux Falls, Rapid City, Aberdeen, and Brookings with reliable Midwest carriers.',
    bannerImage: '/assets/state/dakota.webp',
    majorCities: ['Sioux Falls', 'Rapid City', 'Aberdeen', 'Brookings', 'Pierre'],
    popularRoutes: [{ from: 'South Dakota to Texas', to: 'Texas to South Dakota' }, { from: 'South Dakota to Washington', to: 'Washington to South Dakota' }],
    step1: { title: 'Get your instant South Dakota car shipping quote', text: 'Book with South Dakota\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/dakota-1.webp' },
    step2: { title: 'We arrange auto shipping that South Dakota residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/dakota-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within South Dakota is hassle-free with BMD Freight.', image: '/assets/state/dakota-3.webp' }
  },
  tennessee: {
    name: 'Tennessee',
    slug: 'tennessee',
    title: 'Tennessee Car Shipping Services',
    description: 'Tennessee car shipping with BMD Freight. We transport vehicles to and from Nashville, Memphis, Knoxville, and Chattanooga with professional service.',
    bannerImage: '/assets/state/tennessee.webp',
    majorCities: ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga', 'Clarksville'],
    popularRoutes: [{ from: 'Tennessee to Florida', to: 'Florida to Tennessee' }, { from: 'Tennessee to Texas', to: 'Texas to Tennessee' }],
    step1: { title: 'Get your instant Tennessee car shipping quote', text: 'Book with Tennessee\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/tennessee-1.webp' },
    step2: { title: 'We arrange auto shipping that Tennessee residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/tennessee-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Tennessee is hassle-free with BMD Freight.', image: '/assets/state/tennessee-3.webp' }
  },
  texas: {
    name: 'Texas',
    slug: 'texas',
    title: 'Texas Car Shipping Services',
    description: 'Ship your car safely to or from Texas with BMD Freight\'s expert transport services.',
    bannerImage: '/assets/state/texas.webp',
    majorCities: ['Houston', 'Dallas', 'Austin', 'San Antonio', 'Fort Worth'],
    popularRoutes: [{ from: 'Texas to California', to: 'California to Texas' }, { from: 'Texas to Florida', to: 'Florida to Texas' }],
    step1: { title: 'Get your instant Texas car shipping quote', text: 'Book with Texas\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/texas-1.webp' },
    step2: { title: 'We arrange auto shipping that Texas residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/texas-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Texas is hassle-free with BMD Freight.', image: '/assets/state/texas-3.webp' }
  },
  utah: {
    name: 'Utah',
    slug: 'utah',
    title: 'Utah Car Shipping Services',
    description: 'Ship your car to or from Utah with BMD Freight. We serve Salt Lake City, Provo, Ogden, and St. George with reliable Mountain West auto transport.',
    bannerImage: '/assets/state/utah.webp',
    majorCities: ['Salt Lake City', 'Provo', 'Ogden', 'St. George', 'Sandy'],
    popularRoutes: [{ from: 'Utah to California', to: 'California to Utah' }, { from: 'Utah to Texas', to: 'Texas to Utah' }],
    step1: { title: 'Get your instant Utah car shipping quote', text: 'Book with Utah\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/utah-1.webp' },
    step2: { title: 'We arrange auto shipping that Utah residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/utah-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Utah is hassle-free with BMD Freight.', image: '/assets/state/utah-3.webp' }
  },
  vermont: {
    name: 'Vermont',
    slug: 'vermont',
    title: 'Vermont Car Shipping Services',
    description: 'Vermont car shipping with BMD Freight. We serve Burlington, Montpelier, Rutland, and South Burlington with professional New England transport.',
    bannerImage: '/assets/state/vermont.webp',
    majorCities: ['Burlington', 'Montpelier', 'Rutland', 'South Burlington', 'Barre'],
    popularRoutes: [{ from: 'Vermont to Florida', to: 'Florida to Vermont' }, { from: 'Vermont to New York', to: 'New York to Vermont' }],
    step1: { title: 'Get your instant Vermont car shipping quote', text: 'Book with Vermont\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/vermont-1.webp' },
    step2: { title: 'We arrange auto shipping that Vermont residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/vermont-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Vermont is hassle-free with BMD Freight.', image: '/assets/state/vermont-3.webp' }
  },
  virginia: {
    name: 'Virginia',
    slug: 'virginia',
    title: 'Virginia Car Shipping Services',
    description: 'Auto transport to and from Virginia made easy. BMD Freight serves Virginia Beach, Richmond, Norfolk, and Arlington with reliable East Coast carriers.',
    bannerImage: '/assets/state/virginia.webp',
    majorCities: ['Virginia Beach', 'Richmond', 'Norfolk', 'Arlington', 'Alexandria'],
    popularRoutes: [{ from: 'Virginia to Florida', to: 'Florida to Virginia' }, { from: 'Virginia to New York', to: 'New York to Virginia' }],
    step1: { title: 'Get your instant Virginia car shipping quote', text: 'Book with Virginia\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/virginia-1.webp' },
    step2: { title: 'We arrange auto shipping that Virginia residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/virginia-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Virginia is hassle-free with BMD Freight.', image: '/assets/state/virginia-3.webp' }
  },
  washington: {
    name: 'Washington',
    slug: 'washington',
    title: 'Washington Car Shipping Services',
    description: 'Washington state car shipping experts. BMD Freight moves vehicles to and from Seattle, Spokane, Tacoma, and Vancouver with professional Pacific Northwest service.',
    bannerImage: '/assets/state/washington.webp',
    majorCities: ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue'],
    popularRoutes: [{ from: 'Washington to California', to: 'California to Washington' }, { from: 'Washington to Texas', to: 'Texas to Washington' }],
    step1: { title: 'Get your instant Washington car shipping quote', text: 'Book with Washington\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/washington-1.webp' },
    step2: { title: 'We arrange auto shipping that Washington residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/washington-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Washington is hassle-free with BMD Freight.', image: '/assets/state/washington-3.webp' }
  },
  'west-virginia': {
    name: 'West Virginia',
    slug: 'west-virginia',
    title: 'West Virginia Car Shipping Services',
    description: 'Car shipping to and from West Virginia with BMD Freight. We serve Charleston, Huntington, Morgantown, and Parkersburg with reliable Appalachian transport.',
    bannerImage: '/assets/state/west.webp',
    majorCities: ['Charleston', 'Huntington', 'Morgantown', 'Parkersburg', 'Wheeling'],
    popularRoutes: [{ from: 'West Virginia to Florida', to: 'Florida to West Virginia' }, { from: 'West Virginia to Texas', to: 'Texas to West Virginia' }],
    step1: { title: 'Get your instant West Virginia car shipping quote', text: 'Book with West Virginia\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/west-1.webp' },
    step2: { title: 'We arrange auto shipping that West Virginia residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/west-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within West Virginia is hassle-free with BMD Freight.', image: '/assets/state/west-3.webp' }
  },
  wisconsin: {
    name: 'Wisconsin',
    slug: 'wisconsin',
    title: 'Wisconsin Car Shipping Services',
    description: 'Wisconsin auto transport with BMD Freight. We serve Milwaukee, Madison, Green Bay, and Kenosha with professional Midwest car shipping.',
    bannerImage: '/assets/state/wisconsin.webp',
    majorCities: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha', 'Racine'],
    popularRoutes: [{ from: 'Wisconsin to Florida', to: 'Florida to Wisconsin' }, { from: 'Wisconsin to Texas', to: 'Texas to Wisconsin' }],
    step1: { title: 'Get your instant Wisconsin car shipping quote', text: 'Book with Wisconsin\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/wisconsin-1.webp' },
    step2: { title: 'We arrange auto shipping that Wisconsin residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/wisconsin-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Wisconsin is hassle-free with BMD Freight.', image: '/assets/state/wisconsin-3.webp' }
  },
  wyoming: {
    name: 'Wyoming',
    slug: 'wyoming',
    title: 'Wyoming Car Shipping Services',
    description: 'Car shipping to and from Wyoming. BMD Freight serves Cheyenne, Casper, Laramie, and Gillette with experienced carriers for rural and mountain routes.',
    bannerImage: '/assets/state/wyoming.webp',
    majorCities: ['Cheyenne', 'Casper', 'Laramie', 'Gillette', 'Rock Springs'],
    popularRoutes: [{ from: 'Wyoming to California', to: 'California to Wyoming' }, { from: 'Wyoming to Texas', to: 'Texas to Wyoming' }],
    step1: { title: 'Get your instant Wyoming car shipping quote', text: 'Book with Wyoming\'s most reliable auto transport company for a free, no-obligation quote!', image: '/assets/state/wyoming-1.webp' },
    step2: { title: 'We arrange auto shipping that Wyoming residents rely on', text: 'BMD Freight offers unmatched flexibility and a reputation for excellence.', image: '/assets/state/wyoming-2.webp' },
    step3: { title: 'Pay for your vehicle transport on your schedule', text: 'Shipping your vehicle to, from, or within Wyoming is hassle-free with BMD Freight.', image: '/assets/state/wyoming-3.webp' }
  },
};

export const stateSlugs = Object.keys(statesData);
